# WARNING : if using Volumes, you have to modify the folder right on the host.
# INFORMATION : To commentdecomment on Notepad++, use Ctrl+K / Ctrk+Q
 

#####################
# Individual version
#####################
version: "3.5"
services:
  nodered:
    build: ./nodered-config
    container_name : nodered
    networks:
      - LoraNetwork
    ports:
      - "1880:1880"
    volumes:
      - ./data/nodered/:/data 
      - ./nodered-config/settings.js:/data/settings.js  
    restart: on-failure
    
influxdb:
    image: "influxdb"
    container_name: influxdb
    networks:
      - LoraNetwork
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb/:/var/lib/influxdb 
    environment:
      - INFLUXDB_DB=maBase 
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    restart: on-failure    

networks:
  LoraNetwork: 
    name: loraNetwork



